# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# test commit123456


name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Stop pm2
      run: |
          pm2 stop 0 && pm2 stop 1
    - name: Install dependencies
      run: |
        npm ci --verbose
      timeout-minutes: 10
    - run: npm run build --if-present

    

    - name: Restart the application with PM2
      run: |
        pm2 restart 0 && pm2 restart 1
